image: gradle:alpine

stages:
  - build
  - test
  
build:
  stage: build
  script:
    - cd component 
    - gradle assemble
  
test:
  stage: test
  script:
    - cd component 
    - gradle check
 
