image: java:8

stages:
  - continuose-integration
  - deploy-backend
  - deploy-frontend
  - acceptance-test
  - destroy

  
build-backend:
  image: java:8
  stage: continuose-integration
  script:
    - cd component 
    - ./gradlew clean assemble 
    - cd ..
  artifacts:
    paths:
      - component/build/libs/component.jar

build-frontend:
  image: node:lts
  stage: continuose-integration
  before_script:
    - rm -rf /var/lib/apt/lists/*
    - apt-get update
    - apt-cache gencaches
    - apt-get install -y zip 
  script:
    - cd frontend
    - npm i
    - npm run build-server
    - cd server-build
    - zip index.zip index.js
    - cd ..
  artifacts:
    paths:
      - frontend/server-build/index.zip

test-backend:
  image: java:8
  stage: continuose-integration
  script:
    - cd component 
    - ./gradlew check
 
test-frontend:
  image: node:lts
  stage: continuose-integration
  script:
    - cd frontend 
    - npm i
    - export REACT_APP_USE_MSW=true
    - export REACT_APP_BACKEND_URL=http://localhost:3000
    - npm test

deploy-frontend:
  stage: deploy-frontend
  image: pulumi/pulumi-nodejs
  script:
    - cd frontend
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi config set REACT_APP_USE_MSW false
    - pulumi config set REACT_APP_BACKEND_URL $(cat ../../component/deployment/backend.env)
    - pulumi up -y
    - FRONTEND_URL=$(pulumi stack output  url)
    - touch cypress.env
    - echo CYPRESS_BASE_URL="$FRONTEND_URL" >> cypress.env
    - touch frontend.env
    - echo REACT_APP_FRONTEND_URL="$FRONTEND_URL" >> frontend.env
    - cd ../..  
  dependencies:
      - build-frontend
      - deploy-backend
  environment:
    name: test
    url: $FRONTEND_URL
  artifacts:
   paths:
     - frontend/deployment/cypress.env
     - frontend/deployment/frontend.env
    
 
deploy-backend:
  stage: deploy-backend
  image: pulumi/pulumi-nodejs
  variables:
     DATABASE_URL: " "
  script:
    - cd database
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi up -y
    - touch database.env
    - DATABASE_URL=jdbc:postgresql://$(pulumi stack output  endpoint)
    - cd ../..  
    - cd component 
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi config set DATABASE_URL "$DATABASE_URL" 
    - pulumi up -y
    - touch backend.env
    - echo $(pulumi stack output  url) >> backend.env
    - cat backend.env
    - cd ../..
  artifacts:
    paths:
      - component/deployment/backend.env
  dependencies:
    - build-backend
 

backend-acceptance-test:
   stage: acceptance-test
   image: java:8
   script:
     - cd backendAcceptanceTest
     - cat ../component/deployment/backend.env
     - export $REACT_APP_BACKEND_URL=$(cat ../component/deployment/backend.env)
     - echo $REACT_APP_BACKEND_URL
     - ./gradlew cucumber
   dependencies:
     - deploy-backend
  
   
acceptrance-test:
   stage: acceptance-test
   image: cypress/base
   script:
     - cd acceptanceTest
     - npm ci
     - cat ../frontend/deployment/cypress.env
     - export $(cat ../frontend/deployment/cypress.env)
     - echo $CYPRESS_BASE_URL
     - npm run cypress-run
   dependencies:
     - deploy-frontend
   
destroy-backend:
  stage: destroy
  image: pulumi/pulumi-nodejs
  script:
    - cd database
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi destroy -y
    - cd ../..  
    - cd component 
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi destroy -y
    - cd ../..

destroy-frontend:
  stage: destroy
  image: pulumi/pulumi-nodejs
  script:
    - cd frontend
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi destroy -y
    - cd ../.. 