image: java:8
stages:
  - build
  - integration-test
  - deploy
  - acceptance-test
  - destroy
  
build:
  image: java:8
  stage: build
  script:
    - cd component 
    - ./gradlew clean assemble -PdisableIntegrationTests

test-backend:
  image: java:8
  stage: integration-test
  script:
    - cd component 
    - ./gradlew check -PdisableIntegrationTests
 
test-frontend:
  image: node
  stage: integration-test
  script:
    - cd frontend 
    - npm i
    - npm test
 
deploy-backend:
  stage: deploy
  image: pulumi/pulumi-nodejs
  script:
    - cd database
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev

    - pulumi up -y
    - pulumi stack select dev
    - echo "spring.datasource.url=jdbc:postgresql://$(pulumi stack output  endpoint )/mydb" >> ../../component/src/main/resources/staging.application.properites
    - echo "BACKEND_URL=$(pulumi stack output  endpoint )" >> staging.env
    - cd ../..
  artifacts:
    reports:
      dotenv: staging.env

backend-acceptrance-test:
   stage: acceptance-test
   image: java:8
   script:
     - cd acceptancetest
     - echo "$BACKEND_URL"
     - export BACKEND_URL="$BACKEND_URL"
     - echo $BACKEN_URL
     - ./gradlew cucumber
   dependencies:
      - deploy-backend
     
