image: java:8
stages:
  - continuose-integration
  - deploy
  - acceptance-test
  - destroy
variables:
  FRONTEND_URL: " "
  BACKEND_URL: " "
  ADATABASE_URL: " "
  
build-backend:
  image: java:8
  stage: continuose-integration
  script:
    - cd component 
    - ./gradlew clean assemble 
    - cd ..
  artifacts:
    paths:
      - component/build/libs/component.jar

build-frontend:
  image: node:lts
  stage: continuose-integration
  before_script:
    - rm -rf /var/lib/apt/lists/*
    - apt-get update
    - apt-cache gencaches
    - apt-get install -y zip 
  script:
    - cd frontend
    - npm i
    - npm run build-server
    - cd server-build
    - zip index.zip index.js
    - cd ..
  artifacts:
    paths:
      - frontend/server-build/index.zip

test-backend:
  image: java:8
  stage: continuose-integration
  script:
    - cd component 
    - ./gradlew check
 
test-frontend:
  image: node:lts
  stage: continuose-integration
  script:
    - cd frontend 
    - npm i
    - export REACT_APP_USE_MSW=true
    - export REACT_APP_BACKEND_URL=http://localhost:3000
    - npm test

deploy-frontend:
  stage: deploy
  image: pulumi/pulumi-nodejs
  script:
    - cd frontend
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi config set REACT_APP_USE_MSW false
    - pulumi up -y
    - FRONTEND_URL=$(pulumi stack output  url)
    - cd ../..  
  dependencies:
      - build-frontend
  environment:
    name: test
    url: $FRONTEND_URL
    
 
deploy-backend:
  stage: deploy
  image: pulumi/pulumi-nodejs
  script:
    - cd database
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi up -y
    - ADATABASE_URL=$(pulumi stack output  endpoint)
    - cd ../..  
    - cd component 
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi up -y
    - export DATABASE_URL="$ADATABASE_URL"
    - BACKEND_URL=$(pulumi stack output  url)
    - cd ../..
 

backend-acceptance-test:
   stage: acceptance-test
   image: java:8
   script:
     - cd backendAcceptanceTest
     - export REACT_APP_BACKEND_URL="$BACKEND_URL"
     - echo $REACT_APP_BACKEND_URL
     - export DATABASE_URL="$ADATABASE_URL"
     - echo $DATABASE_URL
     - ./gradlew cucumber
  
   
acceptrance-test:
   stage: acceptance-test
   image: cypress/base
   script:
     - cd acceptanceTest
     - npm ci
     - export CYPRESS_BASE_URL="$FRONTEND_URL"
     - echo "$FRONTEND_URL"
     - echo $CYPRESS_BASE_URL
     - export REACT_APP_FRONTEND_URL="$FRONTEND_URL"
     - echo $REACT_APP_FRONTEND_URL
     - export REACT_APP_BACKEND_URL="$BACKEND_URL"
     - echo "$BACKEND_URL"
     - echo $REACT_APP_BACKEND_URL
     - export DATABASE_URL="$ADATABASE_URL"
     - echo "$ADATABASE_URL"
     - echo $DATABASE_URL
     - npm run cypress-run
   
destroy-backend:
  stage: destroy
  image: pulumi/pulumi-nodejs
  script:
    - cd database
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi destroy -y
    - cd ../..  
    - cd component 
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi destroy -y
    - cd ../..

destroy-frontend:
  stage: destroy
  image: pulumi/pulumi-nodejs
  script:
    - cd frontend
    - cd deployment
    - npm i
    - export PULUMI_ACCESS_TOKEN="$PULUMI_ACCESS_TOKEN"
    - pulumi login
    - pulumi stack select dev
    - pulumi destroy -y
    - cd ../.. 